sudo: required
dist: bionic
language: python
before_install:
  - sudo apt-get update --fix-missing
install:
  - sudo apt-get install -y ffmpeg libopus-dev python-scipy python3-scipy
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2"
  - "pypy3"
script:
  - python test/test.py
after_script:
  - pip install pylama && python -m pylama -i W,E501 pydub/ || true
